=== 24wings/admin-client/docs/json-schema/data-grid.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "description": "数据表格页面的jsonschema",
    "type":"object",
    "properties": {
        "title":{
            "description": "页面标题",
            "type":"string"
        },
        "columns":{
            "type":"array",
            "items": {
                "$ref": "./column-config.json"
            },
            "description": "表格列数组"
        },
        "componentAlias":{
            "description": "使用哪种数据表格",
            "enum": ["DataGrid","TreeView"]

        },
        "dataManager":{
            "description": "数据源",
            "$ref": "./data-manager.json"
        },
        "queryToolbar":{
            "description": "查询工具条",
            "$ref": "./query-toolbar-config.json"
        },
        "editor":{
            "description": "编辑器",
            "$ref": "./editor-config.json"
        }
    },
    "required": ["title","columns","componentAlias","dataManager","queryToolbar"]
}

=== 24wings/admin-client/docs/ui/grid.json
{
    "$schema": "../json-schema/data-grid.json",
    "title": "测试",
    "componentAlias": "DataGrid",
    "columns": [
        {"isPrimaryKey": true,"label": "id","key": "id","componentAlias": "ColumnNumber"},
        {"key": "name","label": "姓名","componentAlias": "ColumnString"},
        {"key": "age","label": "年龄","componentAlias": "ColumnNumber"},
        {"key": "birthDate","label": "生日","componentAlias": "ColumnDate"}
    
    ],
   
    "dataManager": {"adapter": "local","primaryKey": "id","table": "basic-data-grid"},
    "queryToolbar": {"queryFields": [{"key": "name","componentAlias": "FieldString","label": "关键字","condition": "like"}]},
    
    "editor": {
        "fields": [
            {"key": "id","isPrimaryKey": true,"label": "id","componentAlias": "FieldNumber"},
            {"key": "name","isPrimaryKey": true,"label": "名字","componentAlias": "FieldString"},
            {"key": "birthDate","isPrimaryKey": true,"label": "生日","componentAlias": "FieldDate"}
    ],
    "dataManager": {"primaryKey": "id","adapter": "local","table": "basic-data-grid"}}
}
